### PR TITLE
Take interval into account in MorrisExperimentGrid

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
maybe levels should be too ? in the parent constructor it's called delta, is it the same thing ?

**Comment by sofianehaddad** [comment]
@jschueller delta is a NP (levels an Indices) with delta = k / (levels - 1)
Default "k" is one

**Comment by jschueller** [comment]
@sofianehaddad ok it's just for the initialization of the size, so my pr is ok then ?

**Comment by sofianehaddad** [comment]
yes thanks

**Pull request merged**
