### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by sofianehaddad**
The following enables to fix several issues:
 - Within the LHS design as input design, initial points were sometimes translated
 - If one generates twice the same 'path' one of them was removed without generating a new one;

This is fixed now

### CODE REVIEW

**Comment by sofianehaddad** [comment]
@jschueller travis is failing due to some SSL error. How can I fix it ?

**Comment by jschueller** [comment]
It's using the precise openturns mirror, and the python interp in /opt so versions do not match. Try copy the travis config of ottemplate. I'm going afk. See you.

**Comment by jschueller** [comment]
Fixed in #14.

**Review by dbarbier — APPROVED** [review]
+1

**Pull request merged**
